package View;

/**
 *
 * @author Lenovo
 */
public class Editor_View extends javax.swing.JFrame {

    /**
     * Creates new form Editor_View
     */
    public Editor_View() {
        initComponents();
        this.TDES_RButton.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Algorithms_ButtonGroup = new javax.swing.ButtonGroup();
        load_Button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        editor_TextArea = new javax.swing.JTextArea();
        TDES_RButton = new javax.swing.JRadioButton();
        AES_RButton = new javax.swing.JRadioButton();
        blowfish_RButton = new javax.swing.JRadioButton();
        save_Button = new javax.swing.JButton();
        encrypt_Button = new javax.swing.JButton();
        decrypt_Button = new javax.swing.JButton();
        key_TextField = new javax.swing.JTextField();
        Key_Label = new javax.swing.JLabel();
        steganography_button = new javax.swing.JButton();
        malespin_RButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Encryptor");
        setBackground(java.awt.Color.white);

        load_Button.setText("Load");

        editor_TextArea.setColumns(20);
        editor_TextArea.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        editor_TextArea.setLineWrap(true);
        editor_TextArea.setRows(5);
        jScrollPane1.setViewportView(editor_TextArea);

        TDES_RButton.setText("Triple DES");

        AES_RButton.setText("AES");

        blowfish_RButton.setText("Blowfish");

        save_Button.setText("Save");

        encrypt_Button.setText("Encrypt");

        decrypt_Button.setText("Decrypt");

        Key_Label.setText("Key:");

        steganography_button.setText("Steganography");

        malespin_RButton.setText("???");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Key_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(encrypt_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(load_Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(save_Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(decrypt_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(key_TextField)
                            .addComponent(steganography_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TDES_RButton)
                    .addComponent(AES_RButton)
                    .addComponent(blowfish_RButton)
                    .addComponent(malespin_RButton))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(TDES_RButton)
                        .addGap(18, 18, 18)
                        .addComponent(AES_RButton)
                        .addGap(18, 18, 18)
                        .addComponent(blowfish_RButton)
                        .addGap(27, 27, 27)
                        .addComponent(malespin_RButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(key_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Key_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(decrypt_Button)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(encrypt_Button)
                        .addComponent(load_Button)
                        .addComponent(save_Button)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(steganography_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editor_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editor_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editor_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editor_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editor_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton AES_RButton;
    public javax.swing.ButtonGroup Algorithms_ButtonGroup;
    private javax.swing.JLabel Key_Label;
    public javax.swing.JRadioButton TDES_RButton;
    public javax.swing.JRadioButton blowfish_RButton;
    public javax.swing.JButton decrypt_Button;
    public javax.swing.JTextArea editor_TextArea;
    public javax.swing.JButton encrypt_Button;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField key_TextField;
    public javax.swing.JButton load_Button;
    public javax.swing.JRadioButton malespin_RButton;
    public javax.swing.JButton save_Button;
    private javax.swing.JButton steganography_button;
    // End of variables declaration//GEN-END:variables
}
